version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: tp1_test
    ports:
      - '5000:3306'

    expose:
      - '3306'
    volumes:
      - ./mysql1:/var/lib/mysql
volumes:
  my-db: